//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolPC_WebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoolPCEntities : DbContext
    {
        public CoolPCEntities()
            : base("name=CoolPCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Components> Components { get; set; }
        public virtual DbSet<Components_Types> Components_Types { get; set; }
        public virtual DbSet<Configurations> Configurations { get; set; }
        public virtual DbSet<CPU_Coolings> CPU_Coolings { get; set; }
        public virtual DbSet<CPUs> CPUs { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Deliveries_Details> Deliveries_Details { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<GPUs> GPUs { get; set; }
        public virtual DbSet<HDDs> HDDs { get; set; }
        public virtual DbSet<Keyboards> Keyboards { get; set; }
        public virtual DbSet<Motherboards> Motherboards { get; set; }
        public virtual DbSet<Mouses> Mouses { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Orders_Status> Orders_Status { get; set; }
        public virtual DbSet<Payments_Details> Payments_Details { get; set; }
        public virtual DbSet<Power_Supplies> Power_Supplies { get; set; }
        public virtual DbSet<RAMs> RAMs { get; set; }
        public virtual DbSet<SSDs> SSDs { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Configuration_In_Orders> Configuration_In_Orders { get; set; }
    }
}
