//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolPC_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Components
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Components()
        {
            this.Configurations = new HashSet<Configurations>();
        }
    
        public long component_id { get; set; }
        public string model { get; set; }
        public long type_id { get; set; }
        public decimal price { get; set; }
        public long device_id { get; set; }
        public string color { get; set; }
        public Nullable<long> discount_id { get; set; }
    
        public virtual Components_Types Components_Types { get; set; }
        public virtual CPU_Coolings CPU_Coolings { get; set; }
        public virtual CPUs CPUs { get; set; }
        public virtual Discounts Discounts { get; set; }
        public virtual GPUs GPUs { get; set; }
        public virtual HDDs HDDs { get; set; }
        public virtual Keyboards Keyboards { get; set; }
        public virtual Motherboards Motherboards { get; set; }
        public virtual Mouses Mouses { get; set; }
        public virtual Power_Supplies Power_Supplies { get; set; }
        public virtual RAMs RAMs { get; set; }
        public virtual SSDs SSDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configurations> Configurations { get; set; }
    }
}
