//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolPC_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration_In_Orders
    {
        public Nullable<long> configuration_id { get; set; }
        public long order_id { get; set; }
    
        public virtual Configurations Configurations { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
