//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolPC_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDDs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDDs()
        {
            this.Components = new HashSet<Components>();
        }
    
        public long hdd_id { get; set; }
        public string capacity { get; set; }
        public string spindle_speed { get; set; }
        public string latency { get; set; }
        public string data_speed { get; set; }
        public long device_type_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Components> Components { get; set; }
    }
}
