//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolPC_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public long order_id { get; set; }
        public long delivery_details_id { get; set; }
        public long payment_details_id { get; set; }
        public long order_status_id { get; set; }
        public long customer_id { get; set; }
        public string type { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Deliveries_Details Deliveries_Details { get; set; }
        public virtual Configuration_In_Orders Configuration_In_Orders { get; set; }
        public virtual Orders_Status Orders_Status { get; set; }
        public virtual Payments_Details Payments_Details { get; set; }
    }
}
